### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by philipgriggs** [xylo/intellij-postfix-templates#91]
Hello. I'd like to request Golang as a new language. Either:
1. could you add it as a new template
2. I'm happy to do it myself but I'm stuck following the [wiki](https://github.com/xylo/intellij-postfix-templates/wiki/Add-new-language-support), line `Set up IDEA to be able to compile and to start the plugin` since I can't build and run the existing plugin (without modifications). Here are the steps I've tried:

a. checkout the repo
b. open the `.iml` file in IntelliJ
c. change the project SDK to latest (171)
d. add new Maven module
e. added an artefact with main `AddTemplateFileDialogue`
f. imported pom.xml to the maven tool window
g. build artefacts

But when I compile I get errors about missing imports

**Comment by xylo** [comment]
Hi @philipgriggs.  You're right.  My description is outdated and incomplete.  It's indeed not that easy to get the plugin to compile, since it depends on several other plugins now.  I need to improve the description...

**Comment by xylo** [comment]
It took me a bit time to update the wiki, but now I'm ready.

There are two options how to set up the environment (SHORT WAY and LONG WAY).  However, the LONG WAY isn't really that much longer.  And then you have a full featured configuration.

**Comment by philipgriggs** [comment]
Hi @xylo. Thanks for this - I appreciate your help. I have followed the steps in LONG WAY but I still have issues with the lombok and psi dependencies. When I try to run the plugin I get `package lombok does not exist` and `package com.intellij.sql.psi does not exist`, etc... I have the Lombok Plugin and PsiViewer plugin activated.

For feedback, I found the following links would help complement your instructions:
[http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html](http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html)

The `jdk.table` was in a different location for me, as described below
[https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs)

**Comment by xylo** [comment]
You're right.  I completely forgot to add the necessary libs to the project.  I fixed it now.  So I hope it's working now.

BTW, thanks for the feedback.  I will add it to the wiki. :)

**Comment by xylo** [comment]
I'm just testing it myself.  Seems that the first compilation fails with an error.  Just run the compilation again.  The second trial should work.

However, the run configuration is also missing.  I will add it to the guide in the wiki.

**Comment by philipgriggs** [comment]
Thanks again for your help.

I pulled your update but I still have some dependency errors, eg `package com.jetbrains.python.psi does not exist`. It compiles ok if I delete the python folder.

I then built the artefact and installed the plugin from disk. I can see that it installed ok and I can view the settings. However it doesn't recognise any commands, eg `"1".toInt`. This is working ok when I use the plugin downloaded from the marketplace.

**Comment by xylo** [comment]
Are you sure you installed the Python plugin?  The class `com.jetbrains.python.psi ` should be part of it.  Can you check if `$APPLICATION_PLUGINS_DIR$/python/lib/python.jar` exists?

But deleting (or better excluding the directory from compile) is also an option.

Regarding the completion of "1".toInt:
When you first start the run configuration you will see a small popup in the lower right telling you that there are new web templates for CPT (or something similar).  There's also a link in popup window.  You have to click on it to open the settings and then press OK in the settings dialog, so that the web templates get activated.  If the popup does not appear for you, you can also open the settings manually (Ctrl+Alt+S) and then go to _Editor -> Custom Postfix Template_ and then press OK.

**Comment by xylo** [comment]
OK, if you want to add support for a new IDE (GoLand), you also have to add the corresponding IDE dependency to the plugin.xml.  For instance for Rider this is the line

`<depends optional="true">com.intellij.modules.rider</depends>`

For GoLand this should be the line

`<depends optional="true">com.intellij.modules.go</depends>`

**Comment by philipgriggs** [comment]
Thanks. I've modified the plugin.xml and installed the go plugin in IntelliJ. IntelliJ complains that it can't find `com.intellij.modules.go` but it does have `com.intellij.modules.go-capable` and `org.jetbrains.plugins.go`. But even if I include these in my plugin.xml, the postfix expressions aren't showing up in GoLand.

I also modified the jdk.table file to include the jar files (although I don't know which one is needed).

``` xml
<root url="jar://$APPLICATION_PLUGINS_DIR$/intellij-go/lib/intellij-go-183.4588.61.1574.jar!/" type="simple" />
<root url="jar://$APPLICATION_PLUGINS_DIR$/intellij-go/lib/go-utils-183.4588.61.1574.jar!/" type="simple" />
<root url="jar://$APPLICATION_PLUGINS_DIR$/intellij-go/lib/vgo-183.4588.61.1574.jar!/" type="simple" />
<root url="jar://$APPLICATION_PLUGINS_DIR$/intellij-go/lib/template-integration-183.4588.61.1574.jar!/" type="simple" />
```

**Comment by xylo** [comment]
OK.  I managed to get the templates working.

The line

    <root url="jar://$APPLICATION_PLUGINS_DIR$/intellij-go/lib/intellij-go-183.4588.61.1574.jar!/" type="simple" />

is enough.

Moreover I had to do some changes to the Go files.  Here is my patch: [fixed_Go_support.zip](https://github.com/xylo/intellij-postfix-templates/files/2712928/fixed_Go_support.zip)

**Comment by philipgriggs** [comment]
That's great, thanks 😄 

Just one more point - the map `type2psiCondition` in `CustomGoStringPostfixTemplate.Java` I copied from the Java postfix template, but the go template doesn't recognise these different types. What else do I need to change to get type recognition?

**Comment by philipgriggs** [comment]
Ok, this is now working well 👌I've made a pull request for my fork.

**Comment by xylo** [comment]
Thanks, Philip, for implementing the Go support.  I merged your code into the plugin and created a new release (2.8.0). :)

**Comment by philipgriggs** [comment]
Great! I noticed the description on the website also needs updating: https://plugins.jetbrains.com/plugin/9862-custom-postfix-templates
_This plugin lets you define your own postfix templates for Java, Scala, SQL, PHP, Kotlin, Python, Dart, JavaScript, Rust, and Groovy_

I'll add any extra templates if I think of any more that would be useful.

**Comment by xylo** [comment]
Thanks for the hint.  I updated the README.

Yeah.  You can always add/update your web template files.  If you like you can also manage your web template files in one of your own repositories.  The update mechanism does not require the web template files to be hosted in my repo.  But that is just an option.

**Comment by philipgriggs** [comment]
yes, I think it's best if I manage them. I've made a pull request with an updated yaml file
